# This is the project file for the automated build system travis (travis-ci.com).
sudo: false

dist: trusty

language: c

compiler: gcc

addons:
  apt:
    packages:
      - libhidapi-dev

before_install:
  - ./autogen.sh

install: true # skip install step

script: ./configure && make
