# This is the project file for the automated build system travis (travis-ci.com).
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
    - os: osx

language: c

compiler: gcc

addons:
  apt:
    packages:
      - libhidapi-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hidapi; fi
  - ./autogen.sh

install: true # skip install step

script: ./configure && make
